config/routes.rb
DishFlip::Application.routes.draw do
  resources :locations

  resources :meals

  resources :restaurants

   root 'restaurants#index'
   resources :rests

end

app/models/meal.rb
class Meal < ActiveRecord::Base
	belongs_to :restaurant
    validates  :restaurant_id, presence: true

    has_attached_file :meal_photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :meal_photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
    @meal.restaurant_id = params[:restaurant_id]
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)
    @hello = new_meal_path



    respond_to do |format|
      if @meal.save
        format.html { redirect_to @hello, notice: 'Meal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meal }
      else
        format.html { render action: 'new' }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:meal_name, :meal_price, :cuisine_type, :restaurant_id,
                     :meal_photo)
    end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<%= bootstrap_form_for(@meal) do |f| %>
  
  
  <%= f.text_field :meal_name %>
  <%= f.text_field :meal_price %>
  <%= f.text_field :cuisine_type %>
  <%= f.text_field :restaurant_id %>
  <%= f.file_field :meal_photo %>
  <%= f.submit "Submit" %>

<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<table class = "table table-striped">
      <thead>
        <tr>
          <th>Meal Name</th>
          <th>Meal Price</th>
          <th>Cuisine Type</th>
          <th>Picture</th>
          <%= link_to "Home", root_path %>
        </tr> 
      </thead>
      <tbody>
    
    <% @meals.each do |meal| %>
          <tr>
            <td><%= meal.meal_name %></td>
            <td><%= meal.meal_price %></td>
            <td><%= meal.cuisine_type %></td>
            <td><%= image_tag meal.meal_photo.url(:thumb) %></td>
            <!--Put information here 
            <td><%#= rest.meal_name %></td>
            <td><%#= rest.meal_price %></td>
            <td><%#= rest.restaurant_area %></td>
            <td><%#= rest.restaurant_address %></td>
            <td><%#= rest.cuisine_type %></td>
            <td><%#= image_tag rest.picture.url(:thumb) %></td>-->
            <td><%= link_to 'Show', meal %></td>
            <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
            <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New', new_meal_path %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meal name:</strong>
  <%= @meal.meal_name %>
</p>

<p>
  <strong>Meal price:</strong>
  <%= @meal.meal_price %>
</p>

<p>
  <strong>Cuisine type:</strong>
  <%= @meal.cuisine_type %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @meal.restaurant_id %>
</p>

<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>