config/routes.rb
DishFlip::Application.routes.draw do
  resources :locations

  resources :meals

  resources :restaurants

   root 'restaurants#index'
   resources :rests

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :meals
	has_many :locations

	 has_attached_file :restaurant_logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	 validates_attachment_content_type :restaurant_logo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @meals = @restaurant.meals
    @restaurant = Restaurant.find(params[:id]) 
    @meal = Meal.new
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @restaurant }
      else
        format.html { render action: 'new' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

   

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:restaurant_name, :restaurant_logo)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= bootstrap_form_for(@restaurant) do |f| %>
  
  
  <%= f.text_field :restaurant_name %>
  <%= f.file_field :restaurant_logo %>
  <%= f.submit "Submit" %>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurant List</h1><%= link_to 'Create New Restaurant', new_restaurant_path %>
<table class = "table table-striped">
      <thead>
        <tr>
          <th>Restaurant Name</th>
          <th>Logo</th>
         <!-- <th>Meal Price</th>
          <th>Restaurant Area</th>
          <th>Restaurant Address</th>
          <th>Cuisine Type</th>
          <th>Picture</th>-->
        </tr> 
      </thead>
      <tbody>
    
    <% @restaurants.each do |rest| %>
          <tr>
            <td><%= link_to rest.restaurant_name, rest %></td>
            <td><%= image_tag rest.restaurant_logo.url(:thumb) %></td>
           
           <!-- <td><%#= rest.meals.meal_name %></td>
            <td><%#= rest.meal_price %></td>
            <td><%#= rest.restaurant_area %></td>
            <td><%#= rest.restaurant_address %></td>
            <td><%#= rest.cuisine_type %></td>
            <td><%#= image_tag rest.picture.url(:thumb) %></td>-->
            <td><%= link_to 'Show', rest %></td>
            <td><%= link_to 'Edit', edit_restaurant_path(rest) %></td>
            <td><%= link_to 'Destroy', rest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.restaurant_name %>'s Meals</h1>


<table class = "table table-striped">
      <thead>
        <tr>
          <th>Restaurant Name</th>	
          <th>Meal Name</th>
          <th>Meal Price</th>
          <th>Cuisine Type</th>
          <th>Picture</th>
        </tr> 
      </thead>
      <tbody>
    
    <% @restaurant.meals.each do |meal| %>
    			<td><%= @restaurant.restaurant_name %></td>
                <td> <%= meal.meal_name %> </td>
                <td> <%= meal.meal_price %> </td>
                <td> <%= meal.cuisine_type %> </td>
                <td><%= image_tag meal.meal_photo.url(:thumb) %></td>


            <td><%= link_to 'Show', meal %></td>
            <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
            <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    </tbody>
  </table>



<%= link_to 'New Meal', new_meal_path(restaurant_id: @restaurant.id) %></br>


<%= link_to 'Edit Restaurant Name', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>