config/routes.rb
DishFlip::Application.routes.draw do
  resources :locations

  resources :meals

  resources :restaurants

   root 'restaurants#index'
   resources :rests

end

app/models/rest.rb
class Rest < ActiveRecord::Base
	has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/controllers/rests_controller.rb
class RestsController < ApplicationController
  before_action :set_rest, only: [:show, :edit, :update, :destroy]

  # GET /rests
  def index
    @rests = Rest.all
  end

  # GET /rests/1
  def show
  end

  # GET /rests/new
  def new
    @rest = Rest.new
  end

  # GET /rests/1/edit
  def edit
  end

  # POST /rests
  def create
    @rest = Rest.new(rest_params)

    if @rest.save
      redirect_to @rest, notice: 'Rest was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /rests/1
  def update
    if @rest.update(rest_params)
      redirect_to @rest, notice: 'Rest was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /rests/1
  def destroy
    @rest.destroy
    redirect_to rests_url, notice: 'Rest was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rest
      @rest = Rest.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rest_params
      params.require(:rest).permit(:restaurant_name, :meal_name, :meal_price,
       :restaurant_area, :restaurant_address, :cuisine_type, :picture )
    end
end

app/helpers/rests_helper.rb
module RestsHelper
end

app/views/rests/_form.html.erb
<%= bootstrap_form_for(@rest) do |f| %>
  <%= f.text_field :restaurant_name %>
  <%= f.text_field :meal_name %>
  <%= f.text_field :meal_price %>
  <%#= f.text_field :restaurant_area %>

  <%= f.form_group :restaurant_area, :class => "radio-inline", label: { text: "Area"} do %>
        <%= f.radio_button :restaurant_area, "Uptown", label: "Uptown", checked: true %>
        <%= f.radio_button :restaurant_area, "Greenville", label: "Greenville" %>
        <%= f.radio_button :restaurant_area, "Knox-Henderson", label: "Knox-Henderson" %>
        <%= f.radio_button :restaurant_area, "North Dallas", label: "North Dallas" %>
        <%= f.radio_button :restaurant_area, "Addison", label: "Addison" %>
        <%= f.radio_button :restaurant_area, "Trinity Groves", label: "Trinity Groves" %>
        <%= f.radio_button :restaurant_area, "Bishop Arts", label: "Bishop Arts" %>
        <%= f.radio_button :restaurant_area, "Lower Greenville", label: "Lower Greenville" %>
        <%= f.radio_button :restaurant_area, "Downtown", label: "Downtown" %>
        <%= f.radio_button :restaurant_area, "Oak Lawn", label: "Oak Lawn" %>
        <%= f.radio_button :restaurant_area, "Lakewood", label: "Lakewood" %>
    <% end %>




  <%= f.text_field :restaurant_address %>
  <%= f.text_field :cuisine_type %>
  <%= f.file_field :picture %>
  
  <%= f.submit "Submit" %>
<% end %>

app/views/rests/edit.html.erb
<h1>Editing rest</h1>

<%= render 'form' %>

<%= link_to 'Show', @rest %> |
<%= link_to 'Back', rests_path %>

app/views/rests/index.html.erb
<h1>Listing rests</h1>


<table class = "table table-striped">
      <thead>
        <tr>
          <th>Restaurant Name</th>
          <th>Meal Name</th>
          <th>Meal Price</th>
          <th>Restaurant Area</th>
          <th>Restaurant Address</th>
          <th>Cuisine Type</th>
          <th>Picture</th>
        </tr> 
      </thead>
      <tbody>
    
    <% @rests.each do |rest| %>
          <tr>
            <td><%= rest.restaurant_name %></td>
            <td><%= rest.meal_name %></td>
            <td><%= rest.meal_price %></td>
            <td><%= rest.restaurant_area %></td>
            <td><%= rest.restaurant_address %></td>
            <td><%= rest.cuisine_type %></td>
            <td><%= image_tag rest.picture.url(:thumb) %></td>
            <td><%= link_to 'Show', rest %></td>
            <td><%= link_to 'Edit', edit_rest_path(rest) %></td>
            <td><%= link_to 'Destroy', rest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New', new_rest_path %>

app/views/rests/new.html.erb
<h1>New rest</h1> <%= link_to 'Index', rests_path %>

<%= render 'form' %>

<%#= link_to 'Back', rests_path %>

app/views/rests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rest_path(@rest) %> |
<%= link_to 'Back', rests_path %>