config/routes.rb
DishFlip::Application.routes.draw do
  resources :locations

  resources :meals

  resources :restaurants

   root 'restaurants#index'
   resources :rests

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :restaurant
    validates  :restaurant_id, presence: true
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:street_address, :zipcode, :city, :restaurant_id)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :street_address %>
    <%= f.input :zipcode %>
    <%= f.input :city %>
    <%= f.input :restaurant_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Street address</th>
      <th>Zipcode</th>
      <th>City</th>
      <th>Restaurant</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.street_address %></td>
        <td><%= location.zipcode %></td>
        <td><%= location.city %></td>
        <td><%= location.restaurant_id %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street address:</strong>
  <%= @location.street_address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @location.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @location.restaurant_id %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>